spring.application.name=Integration Testing

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=broadcom_db;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Password@123
spring.security.user.name=admin
spring.security.user.password=admin123
#jdbc driver added to classpath as dependency